// <auto-generated />
using System;
using CodePulse.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CodePulse.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260504093959_AddUserPermission")]
    partial class AddUserPermission
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CodePulse.API.Models.Domain.BlogPost", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FeatureImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<DateTime>("PublishedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrlHandle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BlogPosts");
                });

            modelBuilder.Entity("CodePulse.API.Models.Domain.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrlHandle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("CodePulse.API.Models.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobileNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CodePulse.API.Models.Domain.User", b =>
                {
                    b.OwnsOne("CodePulse.API.Models.Domain.UserPermissions", "Permissions", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");

                            b1.OwnsOne("CodePulse.API.Models.Domain.PermissionSet", "Admin", b2 =>
                                {
                                    b2.Property<Guid>("UserPermissionsUserId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<bool>("Delete")
                                        .HasColumnType("bit");

                                    b2.Property<bool>("Read")
                                        .HasColumnType("bit");

                                    b2.Property<bool>("Write")
                                        .HasColumnType("bit");

                                    b2.HasKey("UserPermissionsUserId");

                                    b2.ToTable("Users");

                                    b2.WithOwner()
                                        .HasForeignKey("UserPermissionsUserId");
                                });

                            b1.OwnsOne("CodePulse.API.Models.Domain.PermissionSet", "Employee", b2 =>
                                {
                                    b2.Property<Guid>("UserPermissionsUserId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<bool>("Delete")
                                        .HasColumnType("bit");

                                    b2.Property<bool>("Read")
                                        .HasColumnType("bit");

                                    b2.Property<bool>("Write")
                                        .HasColumnType("bit");

                                    b2.HasKey("UserPermissionsUserId");

                                    b2.ToTable("Users");

                                    b2.WithOwner()
                                        .HasForeignKey("UserPermissionsUserId");
                                });

                            b1.OwnsOne("CodePulse.API.Models.Domain.PermissionSet", "SuperAdmin", b2 =>
                                {
                                    b2.Property<Guid>("UserPermissionsUserId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<bool>("Delete")
                                        .HasColumnType("bit");

                                    b2.Property<bool>("Read")
                                        .HasColumnType("bit");

                                    b2.Property<bool>("Write")
                                        .HasColumnType("bit");

                                    b2.HasKey("UserPermissionsUserId");

                                    b2.ToTable("Users");

                                    b2.WithOwner()
                                        .HasForeignKey("UserPermissionsUserId");
                                });

                            b1.Navigation("Admin")
                                .IsRequired();

                            b1.Navigation("Employee")
                                .IsRequired();

                            b1.Navigation("SuperAdmin")
                                .IsRequired();
                        });

                    b.Navigation("Permissions")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
